import Vue from 'vue';
import Router from 'vue-router';
import store from './../store/store.js';
import Nprogress from 'nprogress';
import 'nprogress/nprogress.css'
Vue.use(Router);
var router = new Router({
  routes:[
    {
      path:'/',
      redirect:'/login'
    },
    {
      path:'/login',
      component:resolve=>require(['@/components/login/login'],resolve)
    },
    {
      path:'/map',
      component:resolve=>require(['@/components/layout/layout'],resolve),
      children:[{
        path:'',
        component:resolve=>require(['@/components/map/map'],resolve)
      }]
    },
    {
      path:'/task',
      component:resolve=>require(['@/components/layout/layout'],resolve),
      children:[
        {
          path:'',
          redirect:'people'
        },
        { 
          path:"people",
          component:resolve=>require(['@/components/task/people'],resolve)
        },
        {
          path:"airplane",
          component:resolve=>require(['@/components/task/airplane'],resolve)
        },
        {
          path:"online",
          component:{
            template:'<h1>online</h1>'
          }
        }
        
      ]
    },{
      path:'/posterror',
      component:resolve=>require(['@/components/layout/layout'],resolve)
    },
    {
      path:'/dataShow',
      component:resolve=>require(['@/components/layout/layout'],resolve),
      children:[
        {
          path:'',
          redirect:'qixiang'
        },
        {
          path:'qixiang',
          component:resolve=>require(['@/components/weather/weather'],resolve)
        },
        {
          path:'ice',
          component:{
            template:'<h1>ice</h1>'
          }
        },
      ]
    },
    {
      path:'/upload',
      component:resolve=>require(['@/components/layout/layout'],resolve),
      children:[
        {
          path:'',
          component:resolve=>require(['@/components/upload/upload.vue'],resolve)
        }
      ]
    },
    {
      path:'/seting',
      component:resolve=>require(['@/components/layout/layout'],resolve),
      children:[
        {
          path:'',
          component:resolve=>require(['@/components/seting/seting.vue'],resolve)
        }
      ]
    }
  ]
});
// 登录控制
const WriteList = ['/login'];
router.beforeEach((to,from,next)=>{
  Nprogress.start();
  //判断是否登录.获取存在本地的token值；
  var islogin = localStorage.getItem('auth');
  if(islogin){
    //已经登录
    //判断即将进入的路由是否是/login;是重定向到task;不是直接next
    if(to.path==='/login')
    {
      next('/map');
    }else{
      next()
    }
  }else{
    //未登录
    //判断即将进入的路由是否是/login;是就直接next;不是，就重定向到login;
    if(WriteList.indexOf(to.path)!==-1)
    {
      next()
    }else{
      next('/login');
      Nprogress.done();
    }
  }
});
router.afterEach((to,from)=>{
  Nprogress.done();
})
export default router;